FROM renegademaster/zomboid-dedicated-server:latest

COPY game-server/amd64-entrypoint.sh /home/steam/amd64-entrypoint.sh
COPY game-server/configure-server.sh /home/steam/configure-server.sh
COPY game-server/mods/ZomboidManager /opt/zm-mod

RUN chmod +x /home/steam/amd64-entrypoint.sh /home/steam/configure-server.sh

ENTRYPOINT ["/bin/bash", "/home/steam/amd64-entrypoint.sh"]
